### ISSUE TITLE
Resubmission checklist

### ISSUE THREAD

**Issue by Aariq** [BrunaLab/HeliconiaDemography#88]
Before re-submitting to GCB:

- [x] Archive this repo on Zenodo (.gitignore data?) and include link in data/code availability statement
- [x] double-check all reviewer comments have been addressed
- [x] proofread revised manuscript
- [x] cover letter explaining updated data
